In [1]:
# Importação do NumPy

import numpy as np

## Tipagem de Dados

In [2]:
# Podemos passar um tipo para o Array por parâmetro

a = np.array([-10, 10, 20, 30], dtype = 'float')

In [3]:
a

array([-10.,  10.,  20.,  30.])

In [4]:
# A propriedade dtype me retorna o tipo dos elementos do array

a.dtype

dtype('float64')

In [5]:
# Caso eu não passe o tipo para o python, ele definirá automaticamente

b = np.array([-10, 10, 20, 30])

In [6]:
b.dtype

dtype('int32')

In [7]:
# Caso exista um elemento diferente dos demais, o Python irá tipar o array pelo elemento mais especifico

c = np.array([10, 20, 30, 40.5])
c.dtype

dtype('float64')

In [8]:
# Podemos também ter um tipo string

d = np.array(['Universidade', 'dos', 'Dados'])

In [9]:
d.dtype

dtype('<U12')

In [10]:
# Array do tipo booleano

e = np.array([False, False, True])
e.dtype

dtype('bool')

## Cast de Arrays

In [11]:
f = np.array([-9, 10, 20.7])
f.dtype

dtype('float64')

In [12]:
# Posso realizar um CAST com a função astype()

f.astype(int)

array([-9, 10, 20])

## Criando Arrays com operações aritméticas em tempo de execução

In [13]:
# Aprendemos que a função arange serve para criar um array

array = np.arange(0,5)
array

array([0, 1, 2, 3, 4])

In [14]:
# Podemos criar o array com qualquer operação aritmética

array = np.arange(0, 10) * 10
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
# Potência

array = np.arange(10) ** 2
array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

## Operações Aritméticas entre Arrays

| 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10|

In [16]:
arrayA = np.arange(0, 10)
arrayB = np.arange(0, 10) + 1

In [17]:
arrayA

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arrayB

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# Soma

arrayA + arrayB

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
# Subtração

arrayA - arrayB

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [21]:
# Divisão

arrayA / arrayB

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ])

In [22]:
# Multiplicação

arrayA * arrayB

array([ 0,  2,  6, 12, 20, 30, 42, 56, 72, 90])

In [23]:
# Comparação de Arrays

arrayA == arrayB

array([False, False, False, False, False, False, False, False, False,
       False])

In [24]:
arrayA > arrayB

array([False, False, False, False, False, False, False, False, False,
       False])

In [25]:
arrayA < arrayB

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [26]:
# Podemos ainda utilizar a tabela da verdade para comparar dois arrays utilizando por exemplo a lógica AND

array1 = np.array([True, False, True, False])
array2 = np.array([False, False, True, False])
np.logical_and(array1, array2)

array([False, False,  True, False])

In [27]:
array1 = np.array([True, False, True, False])
array2 = np.array([False, False, True, False])
np.logical_or(array1, array2)

array([ True, False,  True, False])

# Arrays com tamanhos diferentes

In [28]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([1, 2, 3])

In [29]:
A + B

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [30]:
A * B

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

## Dot Product

In [31]:
A = np.array([2, 4, 6])
B = np.array([2, 2, 2])

In [32]:
# Hamdmard Product
A * B

array([ 4,  8, 12])

In [33]:
# Dot Product
print(np.dot(A, B))

24


In [34]:
A = np.array([3, 7, 10])
B = np.array([9, 3, 2])

In [35]:
# Hoadmard Product

In [36]:
A * B

array([27, 21, 20])

In [37]:
print(np.dot(A, B))

68


## Cópias e Arrays

In [38]:
A = np.arange(10)

In [39]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
B = A[5:]

In [41]:
B

array([5, 6, 7, 8, 9])

In [42]:
A[:] = 0

In [43]:
B

array([0, 0, 0, 0, 0])

In [44]:
A = np.arange(10)

In [45]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
B = A[5:].copy()

In [47]:
B

array([5, 6, 7, 8, 9])

In [48]:
A[:] = 0

In [49]:
B

array([5, 6, 7, 8, 9])