In [1]:
import numpy as np

## Operações com Arrays Multidimensionais

In [2]:
A = [[1, 2, 3, 4], [5, 6, 7, 8], [10, 20, 30, 40], [50, 60, 70, 80]]

array = np.array(A)

print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]


In [3]:
# Primeira linha
print(array[0])

[1 2 3 4]


In [4]:
# linha de indice 2
print(array[2])

[10 20 30 40]


In [5]:
# Primeira linha e última coluna
print(array[0,-1])

4


In [6]:
# Atribuindo um valor a uma posição da matriz
array[0,0] = 0

print(array)

[[ 0  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]


## Trabalhando com intervalos

In [7]:
# Pegando os numeros centrais
print(array[1:3, 1:3])

[[ 6  7]
 [20 30]]


In [8]:
# Pegando o intervalo 7, 8, 30, 40
print(array[1:3, 2:4])

[[ 7  8]
 [30 40]]


In [9]:
# Trazendo somente a última coluna
print(array[-1,:])

[50 60 70 80]


In [10]:
# Conectando arrays multidimensionais
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6]])

C = np.concatenate((A, B))

print(C)

[[1 2]
 [3 4]
 [5 6]]
