## NumPy - Biblioteca matemática, mais utilizada com Álgebra Linear. Vetores e Matrizes.

In [1]:
# Importação do NumPy
import numpy as np

Estruturas Unidimensionais

In [2]:
a1 = np.array(['Spark', 'Hadoop', 'Python', 'R'])

In [3]:
a1

array(['Spark', 'Hadoop', 'Python', 'R'], dtype='<U6')

## Arrays podem ter listas de tipos diferentes

Estruturas Bidmensionais

In [4]:
a2 = np.array([['Altura', 'Largura', 'Profundidade'], [42, 78, 10]])

In [5]:
a2

array([['Altura', 'Largura', 'Profundidade'],
       ['42', '78', '10']], dtype='<U12')

In [6]:
a3 = np.array([[10, 20, 30], [40, 50, 60]])

In [7]:
a3

array([[10, 20, 30],
       [40, 50, 60]])

In [8]:
# Tamanho do Array
print(a1.shape)
print(a2.shape)

(4,)
(2, 3)


In [9]:
# Dimensões do Array
a1.ndim

1

In [10]:
a2.ndim

2

Ausência ou presença de parênteses:

Podemos realizar uma analogia com características e ações. O uso de parênteses reflete uma AÇÃO, equanto a ausência, reflete uma característica.

In [11]:
# O método max() não funciona em arrays de tipos heterogêneo
a3.max()

60

In [12]:
# Atributo
a2.ndim

2

## Método Arrange

In [13]:
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
# usando start/end - de 0 a 100 de 10 em 10
array = np.arange(0, 100, 10)

In [15]:
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Criando estruturas de dados com linspace

In [16]:
# Fique atento: A diferença do linspace para o range é que no arange o últim argumento é o incremento, e no
# linspace o último argumento é o número de elementos do vetor (aleatório)
matriz = np.linspace(0, 10, 20)
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [17]:
matriz = np.linspace(0, 10, 5)
matriz

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
matriz = np.linspace(0, 5, 5)
matriz

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

## Estruturas de Matrizes

In [19]:
# numpy.zeros
matriz = np.zeros((10 ,10))
matriz

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
# Numpy.ones
matriz = np.ones((2, 3))
matriz

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
# Numpy.eye - Produz uma matriz do tipo Identity
matriz = np.eye(10)
matriz

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
# Numpy.diag produz o mesmo resultado, porém podemos definir os números das diagonais
matriz = np.diag((2, 4, 6, 8, 10, 12, 14, 16 ,18, 20))
matriz

array([[ 2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  8,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 14,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 16,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 18,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 20]])

In [23]:
# Numpy.empty produz uma matriz vazia
matriz = np.empty((10, 5))
matriz

array([[ 8.27000674e-312,  8.26981601e-312,  8.53188081e-304,
         2.37106476e-303, -1.04660429e+299],
       [ 1.71207507e-303,  6.07843378e-063,  2.00543126e-303,
         1.78629114e-101,  1.45859711e-303],
       [ 1.64088072e-303,  1.64087637e-303,  8.20796373e-304,
         8.36439795e-299,  9.11575223e-304],
       [ 4.64588662e-217,  1.82315321e-303, -5.11536792e+289,
         1.21930460e-310,  2.09382304e+137],
       [ 6.09972950e+149,  4.97470806e+127,  1.36769260e-313,
         8.18434960e-085,  5.81821776e+180],
       [ 7.05307792e-297,  1.89120937e+219,  4.54253337e+198,
         8.82879322e+199,  7.31467580e-314],
       [ 4.65203811e+151,  1.21572612e-224,  4.55068629e-313,
         8.74601785e-308,  1.33360314e+241],
       [ 3.77248412e-310,  5.08851955e+074,  1.83436589e-312,
         6.18196790e-309,  1.33360294e+241],
       [ 5.67421675e-311,  5.03961303e-266,  3.99046880e-008,
         2.08868046e-310,  7.44046971e-251],
       [ 7.34234302e-270,  1.18456207

## numpy.file

In [24]:
np.tile(np.array([[1, 2], [3, 4], [5, 6]]), 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6]])

In [25]:
# Num de vezes do array na vertical, num de vezes do array na horizontal
np.tile(np.array([[1, 2], [3, 4], [5, 6]]), (3, 6))

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6]])