In [1]:
# Importação do NumPy
import numpy as np

## Tipagem de Dados

In [2]:
# Podemos passar um tipo para o Array por parâmetro
a = np.array([-10, 10, 20, 30], dtype = 'float')

In [3]:
a

array([-10.,  10.,  20.,  30.])

In [4]:
# A propriedade dtype me retorna o tipo dos elementos do array
a.dtype

dtype('float64')

In [5]:
# Caso eu não passe o tipo para o Python, ele definirá automaticamente
b = np.array([-10, 10, 20, 30])
b.dtype

dtype('int32')

In [6]:
# Caso exista um elemento diferente dos demais, o Python irá tipar o array pelo elemento mais específico
c = np.array([10, 20, 30, 40.5])
c.dtype

dtype('float64')

In [7]:
# Podemos também ter um tipo string
d = np.array(['Universidade', 'dos', 'Dados'])

In [8]:
d.dtype

dtype('<U12')

In [9]:
# Array do tipo boleano
e = np.array([False, False, True])

In [10]:
e.dtype

dtype('bool')

## Cast de Arrays

In [11]:
f = np.array([-9, 10, 20.7])
f.dtype

dtype('float64')

In [12]:
# Posso realizar um CAST com a função astype()
f.astype(int)

array([-9, 10, 20])

## Criando Arrays com operações aritméticas em tempo de execução

In [13]:
# Aprendemos que a função arange serve para criar um array
array = np.arange(0,5)
array

array([0, 1, 2, 3, 4])