In [1]:
import numpy as np

In [2]:
a = [1, 2, 11, 6, 8, 18, 2]

array = np.array(a)

print(type(array))

<class 'numpy.ndarray'>


In [3]:
# Verificando o tamanho do array
print(array.shape)

(7,)


In [4]:
# Primeiro Elemento
array[0]

1

In [5]:
# Elemento no índice 2
array[2]

11

In [6]:
# Último Elemento
array[-1]

2

In [7]:
# Trazendo o índice 1 até o 5 (exclusivo)
print(array[1:5])

[ 2 11  6  8]


In [8]:
# utilizando um passo 2 em 2
print(array[1:5:2])

[2 6]


In [9]:
# Trazendo com índices negativos
# -7 representa o primeiro da esquerda e -3 o último a ser trazido (exclusivo)
print(array[-7:-3])

[ 1  2 11  6]


In [10]:
# Índice 3 até o fim
print(array[3:])

[ 6  8 18  2]


In [11]:
# Início até o índice 4
print(array[:4])

[ 1  2 11  6]


In [12]:
# Invertendo o Array - Início até o fim, ao passo de -1
array[::-1]

array([ 2, 18,  8,  6, 11,  2,  1])

In [13]:
# Copiando um Array por referência
b = array[:]
print(b)

[ 1  2 11  6  8 18  2]


In [14]:
# Concatenando 2 Arrays
x = np.array([2, 6, 8, 4])

y = np.array([11, 8, 2])

z = np.concatenate([x, y])

print(z)

[ 2  6  8  4 11  8  2]
