## Matrizes são Objetos ESTRITAMENTE bidimensionais, o que torna mais fácil as Operações Aritméticas

In [1]:
import numpy as np

In [2]:
A = np.matrix([[1, 2], [3, 4]])
B = np.matrix([[5, 3], [8, 7]])

Z = np.array([
    [[2, 6], [8, 4]],
    [[2, 6], [8, 4]],
    [[2, 6], [8, 4]]
])

Y = np.array([2, 6, 8, 4])

In [3]:
print(type(A))

<class 'numpy.matrix'>


In [4]:
print(type(Z))

<class 'numpy.ndarray'>


In [5]:
print(type(Y))

<class 'numpy.ndarray'>


In [6]:
print(A)

[[1 2]
 [3 4]]


In [7]:
print(Z)

[[[2 6]
  [8 4]]

 [[2 6]
  [8 4]]

 [[2 6]
  [8 4]]]


In [8]:
print(Y)

[2 6 8 4]


In [9]:
Z.shape

(3, 2, 2)

In [10]:
Y.shape

(4,)

## Soma

In [11]:
print(A + B)

[[ 6  5]
 [11 11]]


In [12]:
print(B + 3)

[[ 8  6]
 [11 10]]


## Subtração

In [13]:
print(A - B)

[[-4 -1]
 [-5 -3]]


## Multiplicação

In [14]:
A = np.matrix([[1, 2], [3, 4]])

print(A)

[[1 2]
 [3 4]]


In [15]:
# Arrumação em "cruz"
print(A * A)

[[ 7 10]
 [15 22]]


In [16]:
# Multiplicação Índice a Índice
print(np.multiply(A, A))

[[ 1  4]
 [ 9 16]]


## Inversa

In [17]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [18]:
from numpy.linalg import inv

In [19]:
print(inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


## Transposta

In [20]:
print(A.T)

[[1 3]
 [2 4]]
